use_frameworks!

platform :ios, '8.0'

target 'podHelloWorld_Example' do
  pod 'podHelloWorld', :path => '../'

  target 'podHelloWorld_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
